# Generated by Django 3.1.1 on 2020-10-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('standard', models.IntegerField(null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('subject', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Math', 'Math'), ('Physics', 'Physics')], max_length=100, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
